### ISSUE TITLE
可以考虑使用GitHubAction

### ISSUE THREAD

**Issue by usbcsusb** [Ca1se/ClockIn_SUT#1]

**Comment by Ca1se** [comment]
如果我理解的没错的话，GitHub Action 能让这个脚本直接运行在云端，是这样吗？

**Comment by usbcsusb** [comment]
是的，可以把账号密码配置成secret，这样可以利用github提供的服务器，免费运行。

**Comment by Ca1se** [comment]
非常好的建议，我会去实现它

**Comment by Ca1se** [comment]
已添加基于Github Action的自动打卡功能
